 else if("sessionConnection" == name1){this.sessionConnection = value;}
 else if("SessionWindowControl" == name1){this.SessionWindowControl = value;}
 else if("SessionLoggingRB" == name1){this.SessionLoggingRB = value;}
 else if("loggingFileExistsRB" == name1){this.loggingFileExistsRB = value;}
 else if("TerminalLocalEcho" == name1){this.TerminalLocalEcho = value;}
 else if("TerminalLineEditing" == name1){this.TerminalLineEditing = value;}
 else if("keyboardBackspace" == name1){this.keyboardBackspace = value;}
 else if("keyboardHomeKeys" == name1){this.keyboardHomeKeys = value;}
 else if("keyboardFunctionKey" == name1){this.keyboardFunctionKey = value;}
 else if("keyboardInitialState" == name1){this.keyboardInitialState = value;}
 else if("keyboardInitialKeypad" == name1){this.keyboardInitialKeypad = value;}
 else if("bellStyle" == name1){this.bellStyle = value;}
 else if("bellTaskbarCaption" == name1){this.bellTaskbarCaption = value;}
 else if("featuresSecuritySettings" == name1){this.featuresSecuritySettings = value;}
 else if("WhenWindowIsResizedRB" == name1){this.WhenWindowIsResizedRB = value;}
 else if("CursorAppearanceRB" == name1){this.CursorAppearanceRB = value;}
 else if("fontQualityRB" == name1){this.fontQualityRB = value;}
 else if("handleLineDrawingCharRB" == name1){this.handleLineDrawingCharRB = value;}
 else if("actionOfMouseButtonsRB" == name1){this.actionOfMouseButtonsRB = value;}
 else if("defaultSelectionModeRB" == name1){this.defaultSelectionModeRB = value;}
 else if("indicateboldedTextRB" == name1){this.indicateboldedTextRB = value;}
 else if("connectionInternetProtocol" == name1){this.connectionInternetProtocol = value;}
 else if("dataNoSpecifiedUsername" == name1){this.dataNoSpecifiedUsername = value;}
 else if("proxyType" == name1){this.proxyType = value;}
 else if("proxyDNSnameLookup" == name1){this.proxyDNSnameLookup = value;}
 else if("telnetHandlingBSD" == name1){this.telnetHandlingBSD = value;}
 else if("telnetHandlingRFC" == name1){this.telnetHandlingRFC = value;}
 else if("telnetNegotiationPassive" == name1){this.telnetNegotiationPassive = value;}
 else if("telnetNegotiationActive" == name1){this.telnetNegotiationActive = value;}
 else if("sshProtocolVersion" == name1){this.sshProtocolVersion = value;}
 else if("TTYPanelValueRG1" == name1){this.TTYPanelValueRG1 = value;}
 else if("RadioGroup1" == name1){this.RadioGroup1 = value;}
 else if("destinationRG1" == name1){this.destinationRG1 = value;}
 else if("destinationRG2" == name1){this.destinationRG2 = value;}